services:

  portal-app:
    image: portal-php
    container_name: portal-app
    build:
      context: .
      target: dev
      dockerfile: ./build/php/Dockerfile
    entrypoint: php artisan octane:start --server=swoole --host=0.0.0.0 --workers=1 --task-workers=1 --port="${APP_PORT:-80}"
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www:delegated
    ports:
      - "${APP_PORT:-80}:${APP_PORT:-80}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
