services:

  portal-app:
    image: portal-php
    container_name: portal-app
    build:
      context: .
      target: dev
      dockerfile: ./build/php/Dockerfile
    entrypoint: tini -- php -d variables_order=EGPCS artisan octane:start --server=swoole --host=0.0.0.0 --workers=1 --task-workers=1 --port="${APP_PORT:-80}"
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www:delegated
    ports:
      - "${APP_PORT:-80}:${APP_PORT:-80}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mariadb:11.7.1-rc
    container_name: portal-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .docker/db:/var/lib/mysql
    ports:
      - "3306:3306"
